@startuml
class TeamsController {
    + TeamsController(context:MedLedgerDBContext)
    + <<async>> Index() : Task<IActionResult>
    + <<async>> Details(id:int?) : Task<IActionResult>
    + Create() : IActionResult
    + <<async>> Create(team:Team) : Task<IActionResult>
    + <<async>> Edit(id:int?) : Task<IActionResult>
    + <<async>> Edit(id:int, team:Team) : Task<IActionResult>
    + <<async>> Delete(id:int?) : Task<IActionResult>
    + <<async>> DeleteConfirmed(id:int) : Task<IActionResult>
}
Controller <|-- TeamsController
@enduml
