@startuml
class LoginWithRecoveryCodeModel {
    + LoginWithRecoveryCodeModel(signInManager:SignInManager<IdentityUser>, logger:ILogger<LoginWithRecoveryCodeModel>)
    + ReturnUrl : string <<get>> <<set>>
    + <<async>> OnGetAsync(returnUrl:string) : Task<IActionResult>
    + <<async>> OnPostAsync(returnUrl:string) : Task<IActionResult>
}
class InputModel {
    + RecoveryCode : string <<get>> <<set>>
}
PageModel <|-- LoginWithRecoveryCodeModel
LoginWithRecoveryCodeModel --> "Input" InputModel
LoginWithRecoveryCodeModel +-- InputModel
@enduml
