@startuml
!include .\\Program.puml
!include .\\Startup.puml
!include .\\Controllers\AppointmentsController.puml
!include .\\Controllers\ClinicsController.puml
!include .\\Controllers\HomeController.puml
!include .\\Controllers\InventoriesController.puml
!include .\\Controllers\PatientsController.puml
!include .\\Controllers\ProfessionalsController.puml
!include .\\Controllers\ServiceScheduleController.puml
!include .\\Controllers\TeamsController.puml
!include .\\Controllers\UsersController.puml
!include .\\Data\DbInitializer.puml
!include .\\Data\MedLedgerDBContext.puml
!include .\\Migrations\20220625032618_InitialCreate.puml
!include .\\Migrations\20220625032618_InitialCreate.Designer.puml
!include .\\Migrations\20220625033156_FixingCreate_0.0.2.puml
!include .\\Migrations\20220625033156_FixingCreate_0.0.2.Designer.puml
!include .\\Migrations\20220705033020_FixedScaffoldingController_0.0.3.puml
!include .\\Migrations\20220705033020_FixedScaffoldingController_0.0.3.Designer.puml
!include .\\Migrations\20220705034845_FixingDBNamingIssues_0.0.4.puml
!include .\\Migrations\20220705034845_FixingDBNamingIssues_0.0.4.Designer.puml
!include .\\Migrations\20220705043913_AddingScaffoldingViews_0.0.5.puml
!include .\\Migrations\20220705043913_AddingScaffoldingViews_0.0.5.Designer.puml
!include .\\Migrations\20220720045130_AddingInventoryAppointmentTables_0.0.6.puml
!include .\\Migrations\20220720045130_AddingInventoryAppointmentTables_0.0.6.Designer.puml
!include .\\Migrations\20220720045814_AddingInventoryAppointmentTables_0.0.7.puml
!include .\\Migrations\20220720045814_AddingInventoryAppointmentTables_0.0.7.Designer.puml
!include .\\Migrations\20220720051055_AddingAutoIncrementIDs_0.0.8.puml
!include .\\Migrations\20220720051055_AddingAutoIncrementIDs_0.0.8.Designer.puml
!include .\\Migrations\20220720060300_AddingClinicIDToAppointment_0.0.9.puml
!include .\\Migrations\20220720060300_AddingClinicIDToAppointment_0.0.9.Designer.puml
!include .\\Migrations\20220720062628_AddingProfessionalExperience_0.0.10.puml
!include .\\Migrations\20220720062628_AddingProfessionalExperience_0.0.10.Designer.puml
!include .\\Migrations\20220801164528_FixInventoryAppointmentTables_0.0.11.puml
!include .\\Migrations\20220801164528_FixInventoryAppointmentTables_0.0.11.Designer.puml
!include .\\Migrations\20220801164709_FixInventoryAppointmentTables_0.0.12.puml
!include .\\Migrations\20220801164709_FixInventoryAppointmentTables_0.0.12.Designer.puml
!include .\\Migrations\20220801173752_AddClinicServices_0.0.13.puml
!include .\\Migrations\20220801173752_AddClinicServices_0.0.13.Designer.puml
!include .\\Migrations\20220801195100_AddClinicSchedule_0.0.14.puml
!include .\\Migrations\20220801195100_AddClinicSchedule_0.0.14.Designer.puml
!include .\\Migrations\20220801200049_AddClinicScheduleControllerandViews_0.0.15.puml
!include .\\Migrations\20220801200049_AddClinicScheduleControllerandViews_0.0.15.Designer.puml
!include .\\Migrations\20220802131201_AddClinicIDToServiceSchedule_0.0.16.puml
!include .\\Migrations\20220802131201_AddClinicIDToServiceSchedule_0.0.16.Designer.puml
!include .\\Migrations\20220802131334_AddClinicIDToServiceSchedule_0.0.17.puml
!include .\\Migrations\20220802131334_AddClinicIDToServiceSchedule_0.0.17.Designer.puml
!include .\\Migrations\20220802131844_AddClinicIDToServiceSchedule_0.0.17-1.puml
!include .\\Migrations\20220802131844_AddClinicIDToServiceSchedule_0.0.17-1.Designer.puml
!include .\\Migrations\20220802132654_AddClinicIDToServiceSchedule_0.0.18.puml
!include .\\Migrations\20220802132654_AddClinicIDToServiceSchedule_0.0.18.Designer.puml
!include .\\Migrations\20220803024218_TaktTimeEngine_0.0.19.puml
!include .\\Migrations\20220803024218_TaktTimeEngine_0.0.19.Designer.puml
!include .\\Migrations\20220804133938_AddingServiceTimetoServiceSchedule_0.0.20.puml
!include .\\Migrations\20220804133938_AddingServiceTimetoServiceSchedule_0.0.20.Designer.puml
!include .\\Migrations\20220804165150_AddingTaktTimeandResourcesMeasuresaandResourceUnits_0.0.21.puml
!include .\\Migrations\20220804165150_AddingTaktTimeandResourcesMeasuresaandResourceUnits_0.0.21.Designer.puml
!include .\\Migrations\20220804185649_AddingResourceListtoServiceSchedule_0.0.22.puml
!include .\\Migrations\20220804185649_AddingResourceListtoServiceSchedule_0.0.22.Designer.puml
!include .\\Migrations\20220804185946_AddingResourceListtoServiceSchedule_0.0.23.puml
!include .\\Migrations\20220804185946_AddingResourceListtoServiceSchedule_0.0.23.Designer.puml
!include .\\Migrations\20220807212203_AddingResourceListtoServiceSchedule_0.0.24.puml
!include .\\Migrations\20220807212203_AddingResourceListtoServiceSchedule_0.0.24.Designer.puml
!include .\\Migrations\20220807212253_AddingResourceListtoServiceSchedule_0.0.25.puml
!include .\\Migrations\20220807212253_AddingResourceListtoServiceSchedule_0.0.25.Designer.puml
!include .\\Migrations\20220807212328_AddingProfessionalScheduling_0.0.25.puml
!include .\\Migrations\20220807212328_AddingProfessionalScheduling_0.0.25.Designer.puml
!include .\\Migrations\MedLedgerDBContextModelSnapshot.puml
!include .\\Models\Appointment.puml
!include .\\Models\Clinic.puml
!include .\\Models\ErrorViewModel.puml
!include .\\Models\Inventory.puml
!include .\\Models\Patient.puml
!include .\\Models\Professional.puml
!include .\\Models\ServiceSchedule.puml
!include .\\Models\Team.puml
!include .\\Models\User.puml
!include .\\Areas\Identity\IdentityHostingStartup.puml
!include .\\Areas\Identity\Data\MedLedgerMVCContext.puml
!include .\\Areas\Identity\Data\MedLedgerMVCIdentityDbContext.puml
!include .\\Areas\Identity\Pages\Error.cshtml.puml
!include .\\obj\Debug\netcoreapp3.1\.NETCoreApp,Version=v3.1.AssemblyAttributes.puml
!include .\\obj\Debug\netcoreapp3.1\MedLedger.AssemblyInfo.puml
!include .\\obj\Debug\netcoreapp3.1\MedLedger.MvcApplicationPartsAssemblyInfo.puml
!include .\\obj\Debug\netcoreapp3.1\MedLedger.RazorAssemblyInfo.puml
!include .\\obj\Debug\netcoreapp3.1\MedLedger.RazorTargetAssemblyInfo.puml
!include .\\Areas\Identity\Pages\Account\AccessDenied.cshtml.puml
!include .\\Areas\Identity\Pages\Account\ConfirmEmail.cshtml.puml
!include .\\Areas\Identity\Pages\Account\ConfirmEmailChange.cshtml.puml
!include .\\Areas\Identity\Pages\Account\ExternalLogin.cshtml.puml
!include .\\Areas\Identity\Pages\Account\ForgotPassword.cshtml.puml
!include .\\Areas\Identity\Pages\Account\ForgotPasswordConfirmation.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Lockout.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Login.cshtml.puml
!include .\\Areas\Identity\Pages\Account\LoginWith2fa.cshtml.puml
!include .\\Areas\Identity\Pages\Account\LoginWithRecoveryCode.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Logout.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Register.cshtml.puml
!include .\\Areas\Identity\Pages\Account\RegisterConfirmation.cshtml.puml
!include .\\Areas\Identity\Pages\Account\ResetPassword.cshtml.puml
!include .\\Areas\Identity\Pages\Account\ResetPasswordConfirmation.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\ChangePassword.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\DeletePersonalData.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\Disable2fa.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\DownloadPersonalData.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\Email.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\EnableAuthenticator.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\ExternalLogins.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\GenerateRecoveryCodes.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\Index.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\ManageNavPages.puml
!include .\\Areas\Identity\Pages\Account\Manage\PersonalData.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\ResetAuthenticator.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\SetPassword.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\ShowRecoveryCodes.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\TwoFactorAuthentication.cshtml.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\_ViewImports.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\_ViewStart.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Appointments\ConfirmCreate.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Appointments\Create.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Appointments\Delete.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Appointments\Details.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Appointments\Edit.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Appointments\Index.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Clinics\Create.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Clinics\Delete.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Clinics\Details.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Clinics\Edit.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Clinics\Index.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Home\Index.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Home\Index2.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Home\Privacy.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Inventories\Create.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Inventories\Delete.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Inventories\Details.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Inventories\Edit.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Inventories\Index.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Patients\Create.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Patients\Delete.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Patients\Details.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Patients\Edit.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Patients\Index.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Professionals\Create.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Professionals\Delete.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Professionals\Details.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Professionals\Edit.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Professionals\Index.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Professionals\Test.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\ServiceSchedule\Create.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\ServiceSchedule\Delete.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\ServiceSchedule\Details.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\ServiceSchedule\Edit.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\ServiceSchedule\Index.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Shared\Error.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Shared\_Layout.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Shared\_LoginPartial.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Shared\_ValidationScriptsPartial.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Teams\Create.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Teams\Delete.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Teams\Details.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Teams\Edit.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Teams\Index.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Users\Create.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Users\Delete.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Users\Details.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Users\Edit.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Views\Users\Index.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Error.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\_ValidationScriptsPartial.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\_ViewImports.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\_ViewStart.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\AccessDenied.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\ConfirmEmail.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\ConfirmEmailChange.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\ExternalLogin.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\ForgotPassword.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\ForgotPasswordConfirmation.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Lockout.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Login.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\LoginWith2fa.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\LoginWithRecoveryCode.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Logout.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Register.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\RegisterConfirmation.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\ResetPassword.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\ResetPasswordConfirmation.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\_StatusMessage.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\_ViewImports.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\ChangePassword.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\DeletePersonalData.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\Disable2fa.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\DownloadPersonalData.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\Email.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\EnableAuthenticator.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\ExternalLogins.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\GenerateRecoveryCodes.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\Index.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\PersonalData.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\ResetAuthenticator.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\SetPassword.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\ShowRecoveryCodes.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\TwoFactorAuthentication.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\_Layout.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\_ManageNav.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\_StatusMessage.cshtml.g.puml
!include .\\obj\Debug\netcoreapp3.1\Razor\Areas\Identity\Pages\Account\Manage\_ViewImports.cshtml.g.puml
@enduml
